// ═══════════════════════════════════════════════════════════════════
//  RXAI — Complete Clinical Drug Database
//  30 drugs with full pharmacological profiles
//  8 major drug-drug interactions with clinical management
// ═══════════════════════════════════════════════════════════════════

const DRUGS = [
  {
    id: 1, name: 'Amoxicillin', class: 'Antibiotic (Penicillin)',
    min: 250, max: 500, maxDaily: 3000,
    freq: ['BD', 'TDS'], pregnancy: 'B',
    brands: ['Amoxil', 'Trimox', 'Novamox', 'Mox'],
    mechanism: 'Inhibits bacterial cell wall synthesis by binding to penicillin-binding proteins (PBPs), leading to cell lysis.',
    indications: ['Respiratory tract infections', 'Urinary tract infections', 'Otitis media', 'Skin and soft tissue infections', 'H. pylori eradication (with other drugs)'],
    sideEffects: ['Nausea', 'Diarrhoea', 'Skin rash', 'Allergic reaction', 'Anaphylaxis (rare)', 'C. difficile colitis (rare)'],
    contraindications: ['Penicillin hypersensitivity', 'Infectious mononucleosis (risk of rash)'],
    foodInteractions: ['Can be taken with or without food. Avoid grapefruit with extended-release forms.'],
    monitoring: ['Signs of allergic reaction', 'Renal function in prolonged use'],
    halfLife: '1–1.5 hours', route: 'Oral', category: 'antibiotic',
    interactionIds: [8],
  },
  {
    id: 2, name: 'Paracetamol', class: 'Analgesic / Antipyretic',
    min: 325, max: 1000, maxDaily: 4000,
    freq: ['OD', 'BD', 'TDS', 'QDS', 'SOS'], pregnancy: 'B',
    brands: ['Crocin', 'Dolo-650', 'Calpol', 'Tylenol', 'Panadol'],
    mechanism: 'Inhibits prostaglandin synthesis in the CNS; exact mechanism not fully established. Does NOT inhibit peripheral COX significantly.',
    indications: ['Mild-to-moderate pain (headache, toothache, musculoskeletal)', 'Fever (antipyretic)', 'Post-operative pain', 'Safe analgesic in pregnancy'],
    sideEffects: ['Rare at therapeutic doses', 'Hepatotoxicity in overdose', 'Nephrotoxicity with chronic high-dose use', 'Rare: agranulocytosis'],
    contraindications: ['Severe hepatic impairment', 'Paracetamol allergy', 'Alcoholism (relative)'],
    foodInteractions: ['Take with food if GI upset occurs. Avoid alcohol (increases hepatotoxicity risk).'],
    monitoring: ['Liver function tests in chronic use', 'Renal function'],
    halfLife: '1–4 hours', route: 'Oral/IV/Rectal', category: 'analgesic',
    interactionIds: [],
    overdoseInfo: 'DANGER: Therapeutic index is narrow. >150mg/kg or >7.5g in adults = hepatotoxic. Treatment: N-Acetylcysteine (NAC) within 8–10 hours.',
  },
  {
    id: 3, name: 'Metformin', class: 'Antidiabetic (Biguanide)',
    min: 500, max: 1000, maxDaily: 3000,
    freq: ['BD', 'TDS'], pregnancy: 'B',
    brands: ['Glycomet', 'Glucophage', 'Obimet', 'Riomet'],
    mechanism: 'Reduces hepatic glucose production (gluconeogenesis); increases peripheral insulin sensitivity; decreases intestinal glucose absorption. Does NOT cause hypoglycemia alone.',
    indications: ['Type 2 Diabetes Mellitus (first-line)', 'Polycystic ovary syndrome (PCOS)', 'Prediabetes prevention', 'Gestational diabetes (off-label)'],
    sideEffects: ['Nausea', 'Diarrhoea (dose-dependent, take with food)', 'Metallic taste', 'Vitamin B12 deficiency (long-term)', 'Lactic acidosis (rare, serious)'],
    contraindications: ['eGFR < 30 mL/min/1.73m² (CKD G4-5)', 'Lactic acidosis history', 'Hepatic impairment', 'Excessive alcohol intake', 'IV contrast media (hold 48h before/after)'],
    foodInteractions: ['Always take with meals to reduce GI side effects. Avoid alcohol.'],
    monitoring: ['HbA1c every 3 months', 'eGFR annually', 'Vitamin B12 annually', 'Blood glucose'],
    halfLife: '4–9 hours', route: 'Oral', category: 'antidiabetic',
    interactionIds: [28],
  },
  {
    id: 4, name: 'Atorvastatin', class: 'Statin (HMG-CoA Reductase Inhibitor)',
    min: 10, max: 80, maxDaily: 80,
    freq: ['OD'], pregnancy: 'X',
    brands: ['Lipitor', 'Tonact', 'Storvas', 'Atorva'],
    mechanism: 'Competitively inhibits HMG-CoA reductase, the rate-limiting enzyme in cholesterol biosynthesis. Reduces LDL-C by 40–60%; raises HDL; lowers triglycerides.',
    indications: ['Primary hypercholesterolaemia', 'Cardiovascular risk reduction', 'Secondary prevention post-MI or stroke', 'Diabetic dyslipidaemia', 'Familial hypercholesterolaemia'],
    sideEffects: ['Myalgia (muscle aches) — most common', 'Elevated liver enzymes (ALT/AST)', 'Headache', 'GI disturbance', 'Rhabdomyolysis (rare, serious)', 'New-onset diabetes (slightly increased risk)'],
    contraindications: ['Active liver disease', 'Unexplained elevated transaminases', 'Pregnancy (teratogenic)', 'Breastfeeding', 'Concurrent strong CYP3A4 inhibitors (itraconazole, HIV PIs)'],
    foodInteractions: ['Avoid grapefruit/grapefruit juice (inhibits CYP3A4, raises statin levels). Take at any time of day (unlike pravastatin/simvastatin).'],
    monitoring: ['Lipid panel at baseline, 4–12 weeks, then annually', 'LFTs at baseline', 'CK if myalgia occurs', 'Blood glucose'],
    halfLife: '14 hours (active metabolites 20–30h)', route: 'Oral', category: 'statin',
    interactionIds: [8, 17],
  },
  {
    id: 5, name: 'Aspirin', class: 'NSAID / Antiplatelet (Salicylate)',
    min: 75, max: 325, maxDaily: 4000,
    freq: ['OD', 'BD'], pregnancy: 'D',
    brands: ['Ecosprin', 'Disprin', 'Ascard', 'Loprin'],
    mechanism: 'Irreversibly inhibits COX-1 and COX-2, reducing prostaglandin and thromboxane A2 synthesis. Antiplatelet effect: prevents platelet aggregation for the platelet\'s lifespan (~7-10 days).',
    indications: ['Antiplatelet: ACS, post-MI, post-stroke, peripheral arterial disease', 'Analgesic: mild-to-moderate pain', 'Anti-inflammatory: rheumatic fever', 'Low-dose preventive: cardiovascular risk reduction', 'Pre-eclampsia prevention (off-label)'],
    sideEffects: ['GI irritation and bleeding', 'Tinnitus (high doses)', 'Bruising', 'Reye\'s syndrome (children)', 'Aspirin-exacerbated respiratory disease (AERD)', 'Prolonged bleeding time'],
    contraindications: ['Active peptic ulcer disease', 'Haemophilia or bleeding disorders', 'Children < 12 years with viral illness (Reye\'s)', 'Aspirin hypersensitivity/AERD', 'Severe renal or hepatic impairment'],
    foodInteractions: ['Take with food or milk to reduce GI irritation. Avoid alcohol (increases GI bleeding risk).'],
    monitoring: ['Signs of GI bleeding (black stools, haematemesis)', 'INR if combined with warfarin', 'Renal function'],
    halfLife: '15–20 min (aspirin); salicylate 2–3h (low dose), up to 30h (high dose)', route: 'Oral', category: 'nsaid_antiplatelet',
    interactionIds: [6, 17],
  },
  {
    id: 6, name: 'Warfarin', class: 'Anticoagulant (Vitamin K Antagonist)',
    min: 1, max: 10, maxDaily: 15,
    freq: ['OD'], pregnancy: 'X',
    brands: ['Coumadin', 'Warf', 'Sofarin', 'Warfarin Sodium'],
    mechanism: 'Inhibits vitamin K epoxide reductase, preventing regeneration of active vitamin K. This reduces synthesis of vitamin K-dependent clotting factors II, VII, IX, X and anticoagulant proteins C and S.',
    indications: ['Atrial fibrillation (stroke prevention)', 'Deep vein thrombosis (DVT)', 'Pulmonary embolism (PE)', 'Mechanical heart valves', 'Antiphospholipid syndrome'],
    sideEffects: ['Bleeding (major risk — any site)', 'Skin necrosis (rare, day 3–8)', 'Purple toe syndrome', 'Hair loss', 'Teratogenicity'],
    contraindications: ['Active major bleeding', 'Pregnancy (especially 1st trimester and near term)', 'Severe liver disease', 'Recent neurosurgery or eye surgery', 'Unsupervised patients unlikely to comply with monitoring'],
    foodInteractions: ['Maintain CONSISTENT vitamin K intake (leafy greens: spinach, kale, broccoli). Large changes in vitamin K foods dramatically change INR. Avoid cranberry juice (inhibits CYP2C9). Avoid alcohol.'],
    monitoring: ['INR at least weekly when initiating, then monthly when stable. Target INR: 2–3 for most indications; 2.5–3.5 for mechanical mitral valve.'],
    halfLife: '36–42 hours', route: 'Oral', category: 'anticoagulant',
    interactionIds: [5, 10],
    criticalNote: 'NARROW THERAPEUTIC INDEX. INR must be monitored regularly. Many drug-drug and drug-food interactions.',
  },
  {
    id: 7, name: 'Lisinopril', class: 'ACE Inhibitor (Angiotensin-Converting Enzyme Inhibitor)',
    min: 5, max: 40, maxDaily: 80,
    freq: ['OD'], pregnancy: 'D',
    brands: ['Zestril', 'Prinivil', 'Listril', 'Lipril'],
    mechanism: 'Inhibits ACE, preventing conversion of angiotensin I to angiotensin II. Reduces vasoconstriction, aldosterone secretion, and sympathetic activation → lowers BP and reduces cardiac remodelling.',
    indications: ['Hypertension (first-line)', 'Heart failure with reduced ejection fraction', 'Post-MI cardioprotection', 'Diabetic nephropathy (renoprotective)', 'Prevention of CVD events'],
    sideEffects: ['Dry persistent cough (10–15%, due to bradykinin accumulation) — switch to ARB', 'Hypotension (especially first dose)', 'Hyperkalemia', 'Angioedema (rare but life-threatening)', 'Acute kidney injury (in bilateral renal artery stenosis)', 'Teratogenic in 2nd/3rd trimester'],
    contraindications: ['Pregnancy (2nd and 3rd trimester)', 'History of ACE-inhibitor-induced angioedema', 'Bilateral renal artery stenosis', 'Concurrent aliskiren in diabetes/CKD', 'Hyperkalaemia (K⁺ > 5.5 mmol/L)'],
    foodInteractions: ['Avoid salt substitutes containing potassium chloride (hyperkalemia risk). Avoid NSAIDs.'],
    monitoring: ['Blood pressure', 'Serum creatinine and eGFR (baseline, 1–2 weeks after start)', 'Serum potassium', 'Cough assessment'],
    halfLife: '12 hours', route: 'Oral', category: 'ace_inhibitor',
    interactionIds: [10],
  },
  {
    id: 8, name: 'Azithromycin', class: 'Antibiotic (Macrolide)',
    min: 250, max: 500, maxDaily: 500,
    freq: ['OD'], pregnancy: 'B',
    brands: ['Zithromax', 'Azee', 'Azithral', 'Z-pack'],
    mechanism: 'Binds to 50S ribosomal subunit, inhibiting bacterial translocation and protein synthesis. Bacteriostatic (bactericidal at higher concentrations). Has anti-inflammatory properties.',
    indications: ['Community-acquired pneumonia', 'Pharyngitis/tonsillitis (penicillin allergy)', 'Skin and soft tissue infections', 'STIs (Chlamydia, gonorrhea)', 'Atypical pneumonia (Mycoplasma, Chlamydophila, Legionella)', 'MAC prophylaxis in HIV'],
    sideEffects: ['Nausea', 'Diarrhoea', 'Abdominal pain', 'QT interval prolongation (cardiac risk)', 'Hepatotoxicity (rare)', 'Hearing loss (rare, high-dose)'],
    contraindications: ['QT prolongation or Torsades de Pointes history', 'Concurrent QT-prolonging drugs (antiarrhythmics)', 'Severe liver disease', 'Hypersensitivity to macrolides'],
    foodInteractions: ['Take 1 hour before or 2 hours after meals (food reduces absorption for tablets). Avoid antacids containing aluminium/magnesium.'],
    monitoring: ['ECG in patients at cardiac risk', 'LFTs if prolonged use', 'Signs of Clostridium difficile colitis'],
    halfLife: '68 hours (long tissue half-life, short courses effective)', route: 'Oral/IV', category: 'antibiotic',
    interactionIds: [4],
  },
  {
    id: 9, name: 'Ciprofloxacin', class: 'Antibiotic (Fluoroquinolone)',
    min: 250, max: 750, maxDaily: 1500,
    freq: ['BD'], pregnancy: 'C',
    brands: ['Ciprobay', 'Cifran', 'Ciplox', 'Cipro'],
    mechanism: 'Inhibits DNA gyrase (topoisomerase II) and topoisomerase IV, preventing bacterial DNA replication, transcription, and repair. Bactericidal.',
    indications: ['UTI and complicated UTI', 'Pyelonephritis', 'Prostatitis', 'GI infections (traveller\'s diarrhoea, typhoid)', 'Respiratory infections (reserved use)', 'Anthrax prophylaxis/treatment'],
    sideEffects: ['Tendon rupture (especially Achilles) — BLACK BOX WARNING', 'QT prolongation', 'Peripheral neuropathy', 'CNS effects (headache, dizziness, confusion, rare psychosis)', 'Photosensitivity', 'Dysglycaemia'],
    contraindications: ['Previous tendon disorders with fluoroquinolones', 'Children < 18 years (cartilage damage)', 'Myasthenia gravis', 'QT prolongation', 'Concurrent QT-prolonging drugs'],
    foodInteractions: ['Take 2 hours before or 6 hours after dairy products, calcium-fortified foods, antacids (chelation reduces absorption). Avoid caffeine (increases CNS side effects).'],
    monitoring: ['Tendon pain (stop immediately)', 'CNS symptoms', 'Blood glucose in diabetics', 'Renal function'],
    halfLife: '3–5 hours', route: 'Oral/IV', category: 'antibiotic',
    interactionIds: [],
  },
  {
    id: 10, name: 'Ibuprofen', class: 'NSAID (Non-Selective COX Inhibitor)',
    min: 200, max: 400, maxDaily: 2400,
    freq: ['TDS', 'QDS', 'SOS'], pregnancy: 'D',
    brands: ['Brufen', 'Advil', 'Combiflam (with paracetamol)', 'Nurofen'],
    mechanism: 'Non-selectively and reversibly inhibits COX-1 and COX-2, reducing prostaglandin and thromboxane synthesis. Unlike aspirin, this is REVERSIBLE.',
    indications: ['Mild-to-moderate pain (dental, headache, dysmenorrhoea, musculoskeletal)', 'Fever', 'Inflammatory conditions (arthritis)', 'Post-operative pain'],
    sideEffects: ['GI irritation, ulcers, bleeding (COX-1 inhibition)', 'Renal impairment (especially in dehydrated/elderly)', 'Hypertension / fluid retention', 'Cardiovascular risk with long-term use', 'Bronchospasm in AERD/aspirin-sensitive asthma'],
    contraindications: ['Active peptic ulcer disease', 'CKD stage 4-5 (eGFR < 30)', 'Heart failure', 'Aspirin-exacerbated respiratory disease', 'Pregnancy (especially 3rd trimester — premature ductus closure)', 'History of GI bleeding with NSAIDs'],
    foodInteractions: ['Take with food, milk, or antacids to reduce GI irritation. Avoid alcohol.'],
    monitoring: ['BP (NSAIDs raise BP)', 'Renal function (U&E)', 'GI symptoms', 'Cardiac status'],
    halfLife: '2 hours', route: 'Oral/Topical', category: 'nsaid',
    interactionIds: [6, 7],
  },
  {
    id: 11, name: 'Omeprazole', class: 'Proton Pump Inhibitor (PPI)',
    min: 20, max: 40, maxDaily: 80,
    freq: ['OD', 'BD'], pregnancy: 'C',
    brands: ['Omez', 'Prilosec', 'Losec', 'Omepraz'],
    mechanism: 'Irreversibly inhibits the H⁺/K⁺-ATPase (proton pump) on gastric parietal cells. Reduces gastric acid secretion by 80–95%. Effect lasts 3–5 days after stopping.',
    indications: ['GERD and oesophagitis', 'Peptic ulcer disease (gastric and duodenal)', 'H. pylori eradication (part of triple therapy)', 'Zollinger-Ellison syndrome', 'NSAID-induced ulcer prevention', 'Stress ulcer prophylaxis (ICU)'],
    sideEffects: ['Headache', 'Diarrhoea', 'Nausea', 'Hypomagnesaemia (long-term)', 'Vitamin B12 deficiency (long-term)', 'C. difficile risk', 'Bone fractures (prolonged use, high-dose)', 'Hypochlorhydria (increased infection risk)'],
    contraindications: ['Concurrent rilpivirine (HIV drug)', 'Hypersensitivity to PPIs'],
    foodInteractions: ['Take 30–60 minutes BEFORE meals (when proton pumps are active). Do not crush or chew capsules.'],
    monitoring: ['Magnesium levels in prolonged use', 'Vitamin B12 annually', 'DEXA scan if osteoporosis risk'],
    halfLife: '0.5–1 hour (effect lasts 3–5 days)', route: 'Oral/IV', category: 'ppi',
    interactionIds: [],
  },
  {
    id: 12, name: 'Amlodipine', class: 'Calcium Channel Blocker (Dihydropyridine)',
    min: 5, max: 10, maxDaily: 10,
    freq: ['OD'], pregnancy: 'C',
    brands: ['Norvasc', 'Stamlo', 'Amlip', 'Amlopress'],
    mechanism: 'Blocks L-type voltage-gated calcium channels in vascular smooth muscle and cardiac cells. Causes vasodilation (predominantly arterial), reducing peripheral resistance and BP.',
    indications: ['Hypertension (first-line, safe in most populations)', 'Stable and variant (Prinzmetal\'s) angina', 'Raynaud\'s phenomenon'],
    sideEffects: ['Peripheral oedema (ankles) — most common, due to vasodilation not fluid retention', 'Flushing', 'Headache', 'Dizziness', 'Palpitations', 'Gingival hyperplasia (rare)'],
    contraindications: ['Cardiogenic shock', 'Severe aortic stenosis', 'Unstable angina (relative)'],
    foodInteractions: ['Avoid grapefruit/grapefruit juice (inhibits CYP3A4, increases amlodipine levels significantly).'],
    monitoring: ['Blood pressure and heart rate', 'Peripheral oedema assessment', 'Ankle oedema'],
    halfLife: '30–50 hours (very long — allows once-daily dosing)', route: 'Oral', category: 'ccb',
    interactionIds: [],
  },
  {
    id: 13, name: 'Losartan', class: 'ARB (Angiotensin II Receptor Blocker)',
    min: 25, max: 100, maxDaily: 150,
    freq: ['OD', 'BD'], pregnancy: 'D',
    brands: ['Cozaar', 'Losakind', 'Repace', 'Losacar'],
    mechanism: 'Selectively blocks AT1 receptors, preventing angiotensin II-mediated vasoconstriction, aldosterone release, and sympathetic activation. Similar haemodynamic effects to ACE inhibitors but WITHOUT bradykinin accumulation (no cough).',
    indications: ['Hypertension', 'Heart failure (ACE-inhibitor-intolerant patients)', 'Diabetic nephropathy (T2DM with proteinuria)', 'Stroke risk reduction in hypertensive LVH', 'Marfan syndrome (aortic dilation)'],
    sideEffects: ['Dizziness/hypotension', 'Hyperkalemia', 'Renal impairment', 'Fatigue', 'Rarely: angioedema (much less than ACE inhibitors)'],
    contraindications: ['Pregnancy (teratogenic)', 'Bilateral renal artery stenosis', 'Severe hepatic impairment', 'Concurrent aliskiren in DM/CKD', 'Hyperkalaemia'],
    foodInteractions: ['Avoid potassium-rich salt substitutes. Avoid NSAIDs.'],
    monitoring: ['Blood pressure', 'Serum creatinine and eGFR', 'Serum potassium', 'Urine protein (in nephropathy)'],
    halfLife: '2h (losartan), 6–9h (active metabolite E-3174)', route: 'Oral', category: 'arb',
    interactionIds: [],
  },
  {
    id: 14, name: 'Metoprolol', class: 'Beta-1 Selective Blocker (Cardioselective)',
    min: 25, max: 100, maxDaily: 400,
    freq: ['BD'], pregnancy: 'C',
    brands: ['Lopressor', 'Betaloc', 'Metolar', 'Seloken'],
    mechanism: 'Selectively blocks β1-adrenergic receptors in the heart. Reduces heart rate, myocardial contractility, and cardiac output. Lowers BP and oxygen demand. Reduces renin release.',
    indications: ['Hypertension', 'Stable angina', 'Heart failure (metoprolol succinate — HFrEF)', 'Post-MI (mortality reduction)', 'Atrial fibrillation rate control', 'Hyperthyroidism (symptom control)', 'Migraine prophylaxis'],
    sideEffects: ['Bradycardia', 'Fatigue and lethargy', 'Cold extremities', 'Erectile dysfunction', 'Masking hypoglycaemia symptoms (in T1DM)', 'Worsening asthma/COPD (less than non-selective)', 'Depression'],
    contraindications: ['Severe bradycardia (HR < 50)', 'Sick sinus syndrome (without pacemaker)', 'High-degree AV block', 'Decompensated heart failure (do not initiate; continue if already on)', 'Severe asthma/COPD (relative)'],
    foodInteractions: ['Take with food to increase bioavailability. Avoid alcohol (may enhance hypotensive effect).'],
    monitoring: ['Heart rate and BP', 'ECG if arrhythmia concern', 'Blood glucose in diabetics', 'Respiratory symptoms'],
    halfLife: '3–7 hours', route: 'Oral/IV', category: 'beta_blocker',
    interactionIds: [],
  },
  {
    id: 15, name: 'Sertraline', class: 'SSRI Antidepressant',
    min: 50, max: 200, maxDaily: 200,
    freq: ['OD'], pregnancy: 'C',
    brands: ['Zoloft', 'Serta', 'Daxid', 'Lustral'],
    mechanism: 'Selectively inhibits presynaptic serotonin reuptake transporter (SERT), increasing synaptic serotonin concentration. Also has dopaminergic activity at sigma-1 receptors.',
    indications: ['Major depressive disorder', 'Panic disorder', 'PTSD', 'OCD', 'Social anxiety disorder', 'Premenstrual dysphoric disorder (PMDD)'],
    sideEffects: ['Nausea (worst in first 2 weeks, take with food)', 'Insomnia or somnolence', 'Sexual dysfunction (decreased libido, delayed ejaculation)', 'Headache', 'Diarrhoea', 'Hyponatraemia (elderly)', 'Serotonin syndrome (with other serotonergic drugs)', 'Suicidal ideation (black box warning in < 25 years, early treatment)'],
    contraindications: ['Concurrent MAO inhibitors (14-day washout required)', 'Pimozide (QT prolongation)', 'Linezolid or IV methylene blue (serotonin syndrome)'],
    foodInteractions: ['Take with food to reduce GI side effects. Avoid alcohol (CNS depression). Avoid St John\'s Wort (serotonin syndrome).'],
    monitoring: ['Mood and suicidality (especially in < 25y, early treatment)', 'Serum sodium in elderly', 'Sexual function', 'Weight'],
    halfLife: '26 hours', route: 'Oral', category: 'antidepressant',
    interactionIds: [],
  },
  {
    id: 16, name: 'Levothyroxine', class: 'Thyroid Hormone (T4)',
    min: 25, max: 200, maxDaily: 500,
    freq: ['OD'], pregnancy: 'A',
    brands: ['Synthroid', 'Thyronorm', 'Eltroxin', 'Euthyrox'],
    mechanism: 'Synthetic thyroxine (T4) that is converted to triiodothyronine (T3) in peripheral tissues. Regulates metabolism, protein synthesis, growth, and development.',
    indications: ['Hypothyroidism (Hashimoto\'s, post-thyroidectomy, RAI)', 'TSH suppression in thyroid cancer', 'Myxoedema coma (IV)', 'Congenital hypothyroidism (critical to start immediately)'],
    sideEffects: ['At correct dose: none. Overdose effects: palpitations, anxiety, insomnia, weight loss, sweating, diarrhoea, osteoporosis (long-term), AF (elderly)'],
    contraindications: ['Uncorrected adrenal insufficiency (treat adrenal first)', 'Untreated thyrotoxicosis', 'Recent MI or acute myocarditis'],
    foodInteractions: ['Take on EMPTY STOMACH, 30–60 min before breakfast. Calcium, iron, magnesium supplements; dairy; soy; coffee all reduce absorption — take 4h apart. Do NOT take with antacids.'],
    monitoring: ['TSH every 6–8 weeks when adjusting, then annually when stable. Free T4 if TSH abnormal. Bone density with long-term therapy.'],
    halfLife: '6–7 days', route: 'Oral/IV', category: 'thyroid',
    interactionIds: [],
    criticalNote: 'Must take consistently at same time, same way, every day. Even minor dose changes affect TSH.',
  },
  {
    id: 17, name: 'Clopidogrel', class: 'Antiplatelet (P2Y12 ADP Receptor Inhibitor)',
    min: 75, max: 75, maxDaily: 75,
    freq: ['OD'], pregnancy: 'B',
    brands: ['Plavix', 'Clopilet', 'Deplatt', 'Clopivas'],
    mechanism: 'Irreversibly inhibits ADP binding to P2Y12 receptor on platelets, preventing ADP-mediated platelet activation and aggregation. Prodrug — requires CYP2C19 activation.',
    indications: ['ACS (usually with aspirin — DAPT)', 'Post-PCI with stent', 'Peripheral arterial disease', 'Ischaemic stroke/TIA (aspirin-intolerant patients)', 'Post-CABG (off-label)'],
    sideEffects: ['Bleeding (major risk)', 'Bruising', 'GI upset', 'Diarrhoea', 'TTP (thrombotic thrombocytopenic purpura — very rare)', 'Rash'],
    contraindications: ['Active pathological bleeding (peptic ulcer, intracranial)', 'Severe liver impairment', 'CYP2C19 poor metabolisers (genetic — reduced efficacy)', 'Concurrent omeprazole (reduces efficacy — prefer pantoprazole)'],
    foodInteractions: ['Can be taken with or without food. Avoid alcohol (bleeding risk). Avoid grapefruit.'],
    monitoring: ['CBC for bleeding signs', 'Signs of TTP (neurological symptoms, fever, purpura)', 'Bleeding events'],
    halfLife: '6 hours (irreversible platelet effect ~10 days)', route: 'Oral', category: 'antiplatelet',
    interactionIds: [5],
  },
  {
    id: 18, name: 'Insulin Glargine', class: 'Long-Acting Basal Insulin Analogue',
    min: 10, max: 100, maxDaily: 200,
    freq: ['OD'], pregnancy: 'B',
    brands: ['Lantus', 'Toujeo', 'Basalog', 'Glaritus'],
    mechanism: 'Modified insulin analogue with IEP at pH 7, forming microprecipitates subcutaneously. Slow, consistent absorption provides peakless 24-hour basal insulin coverage.',
    indications: ['Type 1 Diabetes Mellitus (basal component)', 'Type 2 DM requiring insulin (when oral agents insufficient)', 'Gestational diabetes (specialist initiated)'],
    sideEffects: ['Hypoglycaemia (serious, dose-dependent)', 'Weight gain', 'Injection site reactions (lipohypertrophy, lipoatrophy)', 'Oedema (initiation)', 'Hypokalaemia'],
    contraindications: ['Hypoglycaemia episode (hold dose, treat)', 'Do NOT mix with other insulins', 'Do NOT give IV (subcutaneous only)'],
    foodInteractions: ['Maintain consistent carbohydrate intake. Alcohol increases hypoglycaemia risk significantly (impairs gluconeogenesis).'],
    monitoring: ['Fasting glucose daily (target 80–130 mg/dL)', 'HbA1c every 3 months', 'Injection site rotation', 'Signs of hypoglycaemia'],
    halfLife: '12 hours (effect 24h)', route: 'Subcutaneous injection only', category: 'insulin',
    interactionIds: [],
    criticalNote: 'Do NOT mix in same syringe with other insulin types. Rotate injection sites to prevent lipohypertrophy.',
  },
  {
    id: 19, name: 'Gabapentin', class: 'Anticonvulsant / Neuropathic Pain Agent',
    min: 300, max: 600, maxDaily: 3600,
    freq: ['TDS'], pregnancy: 'C',
    brands: ['Neurontin', 'Gabantin', 'Gabator', 'Gabapin'],
    mechanism: 'Binds to α2δ subunit of voltage-gated calcium channels in CNS, reducing excitatory neurotransmitter release. Structurally related to GABA but does NOT bind GABA receptors.',
    indications: ['Postherpetic neuralgia', 'Diabetic peripheral neuropathy', 'Partial seizures (adjunctive)', 'Restless legs syndrome', 'Fibromyalgia (off-label)', 'Alcohol withdrawal (off-label)'],
    sideEffects: ['Dizziness (dose-limiting)', 'Somnolence', 'Ataxia (poor coordination)', 'Peripheral oedema', 'Weight gain', 'Blurred vision', 'Respiratory depression (high doses, elderly, combination with opioids)'],
    contraindications: ['Hypersensitivity', 'Concurrent CNS depressants (relative — risk of respiratory depression)'],
    foodInteractions: ['Can be taken with or without food. Food may increase absorption. Avoid alcohol (additive CNS depression).'],
    monitoring: ['Renal function (dose adjust in CKD)', 'Signs of CNS depression', 'Respiratory status (in combination with opioids)'],
    halfLife: '5–7 hours', route: 'Oral', category: 'anticonvulsant',
    interactionIds: [],
  },
  {
    id: 20, name: 'Prednisone', class: 'Corticosteroid (Systemic)',
    min: 5, max: 60, maxDaily: 80,
    freq: ['OD', 'BD'], pregnancy: 'C',
    brands: ['Wysolone', 'Deltasone', 'Omnacortil', 'Prednisolone (active metabolite)'],
    mechanism: 'Converted to active prednisolone. Binds glucocorticoid receptor, modulating gene transcription. Broad anti-inflammatory and immunosuppressive effects. Also has mineralocorticoid activity.',
    indications: ['Inflammatory conditions (asthma, COPD exacerbation)', 'Autoimmune diseases (lupus, RA, IBD)', 'Organ transplant rejection prevention', 'Severe allergic reactions', 'Adrenal insufficiency', 'Nephrotic syndrome'],
    sideEffects: ['Short-term: insomnia, mood changes, hyperglycaemia, increased appetite', 'Long-term: Cushing\'s syndrome, osteoporosis, avascular necrosis, cataracts, hypertension, diabetes, immunosuppression, HPA axis suppression'],
    contraindications: ['Systemic fungal infection', 'Live vaccines in immunosuppressed', 'Abrupt discontinuation after prolonged use (risk of adrenal crisis)'],
    foodInteractions: ['Take with food or milk to reduce GI irritation. Avoid alcohol. Calcium and vitamin D supplementation recommended for bone protection. Avoid grapefruit.'],
    monitoring: ['Blood glucose', 'Blood pressure', 'Bone density (DEXA) with prolonged use', 'Eye examination', 'Weight', 'Electrolytes'],
    halfLife: '2–3 hours (prednisolone); biological effect 18–36h', route: 'Oral/IV/IM', category: 'corticosteroid',
    interactionIds: [],
  },
  {
    id: 21, name: 'Furosemide', class: 'Loop Diuretic',
    min: 20, max: 80, maxDaily: 600,
    freq: ['OD', 'BD'], pregnancy: 'C',
    brands: ['Lasix', 'Frusenex', 'Frusol', 'Fuside'],
    mechanism: 'Inhibits the Na⁺/K⁺/2Cl⁻ cotransporter (NKCC2) in the thick ascending loop of Henle, preventing sodium and water reabsorption. Potent diuresis within 1 hour of oral dose.',
    indications: ['Heart failure (acute and chronic)', 'Oedema (renal, hepatic, pulmonary)', 'Hypertension (resistant, or with CKD)', 'Hypercalcaemia', 'Acute pulmonary oedema (IV)'],
    sideEffects: ['Hypokalaemia (potassium loss — most common)', 'Hyponatraemia', 'Dehydration', 'Orthostatic hypotension', 'Ototoxicity (high IV doses — deafness)', 'Hyperuricaemia (gout)', 'Hypomagnesaemia'],
    contraindications: ['Anuria (not expected to respond)', 'Hepatic coma', 'Hypersensitivity to sulfonamides (relative)', 'Severe electrolyte depletion'],
    foodInteractions: ['Take in morning to prevent nocturia. Potassium-rich foods help: bananas, potatoes, oranges. Avoid liquorice (worsens hypokalaemia).'],
    monitoring: ['Serum electrolytes (K⁺, Na⁺, Mg²⁺) regularly', 'Fluid balance / weight daily', 'Renal function', 'BP (orthostatic)'],
    halfLife: '2 hours', route: 'Oral/IV/IM', category: 'diuretic',
    interactionIds: [],
  },
  {
    id: 22, name: 'Rosuvastatin', class: 'Statin (HMG-CoA Reductase Inhibitor)',
    min: 5, max: 40, maxDaily: 40,
    freq: ['OD'], pregnancy: 'X',
    brands: ['Crestor', 'Rozavel', 'Rosuvas', 'Rosulip'],
    mechanism: 'More potent HMG-CoA reductase inhibitor than atorvastatin. Less CYP3A4 metabolism (fewer drug interactions). Greater LDL-C reduction per mg dose.',
    indications: ['Primary hypercholesterolaemia', 'Hypertriglyceridaemia', 'Cardiovascular risk reduction', 'Familial hypercholesterolaemia (higher doses needed)', 'Regression of atherosclerosis'],
    sideEffects: ['Myalgia', 'Elevated liver enzymes', 'Proteinuria (high-dose, especially in Asian patients)', 'Rhabdomyolysis (rare)', 'New-onset T2DM (slightly increased risk)'],
    contraindications: ['Active liver disease', 'Pregnancy', 'Severe renal impairment (avoid > 10mg/day)', 'Concurrent cyclosporine (contraindicated)'],
    foodInteractions: ['No grapefruit restriction (unlike atorvastatin — rosuvastatin not metabolised by CYP3A4). Can be taken at any time.'],
    monitoring: ['Lipid panel', 'LFTs', 'CK if myalgia', 'Urinalysis (protein) at high doses', 'Blood glucose'],
    halfLife: '19 hours', route: 'Oral', category: 'statin',
    interactionIds: [],
  },
  {
    id: 23, name: 'Glimepiride', class: 'Sulfonylurea (2nd Generation)',
    min: 1, max: 4, maxDaily: 8,
    freq: ['OD'], pregnancy: 'C',
    brands: ['Amaryl', 'Glimer', 'Glucoryl', 'Glimpid'],
    mechanism: 'Binds to SUR1 subunit of ATP-sensitive K⁺ channels on pancreatic β-cells, causing depolarisation and insulin secretion. Requires functioning β-cells.',
    indications: ['Type 2 Diabetes Mellitus (as monotherapy or combination with metformin/insulin)'],
    sideEffects: ['Hypoglycaemia (major risk — especially if meal delayed or skipped)', 'Weight gain', 'Nausea', 'Photosensitivity', 'Haematological: agranulocytosis (very rare)'],
    contraindications: ['Type 1 DM', 'Diabetic ketoacidosis', 'Severe renal or hepatic impairment', 'Pregnancy', 'G6PD deficiency'],
    foodInteractions: ['Take with first main meal of day. Never skip meals. Avoid alcohol (severe hypoglycaemia risk).'],
    monitoring: ['Blood glucose (especially fasting)', 'HbA1c every 3 months', 'Renal and hepatic function', 'Weight'],
    halfLife: '5–8 hours', route: 'Oral', category: 'antidiabetic',
    interactionIds: [],
  },
  {
    id: 24, name: 'Ramipril', class: 'ACE Inhibitor',
    min: 2.5, max: 10, maxDaily: 20,
    freq: ['OD', 'BD'], pregnancy: 'D',
    brands: ['Altace', 'Cardace', 'Ramy', 'Ramace'],
    mechanism: 'Prodrug — converted to active ramiprilat. Inhibits ACE. Superior cardiovascular outcome data (HOPE trial: 22% risk reduction in major CV events).',
    indications: ['Hypertension', 'Post-MI heart failure', 'Cardioprotection in high CV risk patients', 'Diabetic and non-diabetic nephropathy', 'Stroke prevention'],
    sideEffects: ['Dry cough', 'Hypotension (first-dose)', 'Hyperkalemia', 'Angioedema (rare)', 'Renal impairment', 'Teratogenic'],
    contraindications: ['Pregnancy', 'Angioedema history', 'Bilateral renal artery stenosis'],
    foodInteractions: ['Avoid potassium supplements and salt substitutes. Avoid NSAIDs.'],
    monitoring: ['BP', 'Serum creatinine', 'Potassium', 'Cough'],
    halfLife: '13–17h (ramiprilat)', route: 'Oral', category: 'ace_inhibitor',
    interactionIds: [],
  },
  {
    id: 25, name: 'Allopurinol', class: 'Xanthine Oxidase Inhibitor (Antigout)',
    min: 100, max: 300, maxDaily: 900,
    freq: ['OD', 'BD'], pregnancy: 'C',
    brands: ['Zyloprim', 'Zyloric', 'Aloric', 'Uricont'],
    mechanism: 'Inhibits xanthine oxidase, the enzyme converting hypoxanthine → xanthine → uric acid. Reduces serum and urinary uric acid levels.',
    indications: ['Chronic gout (prophylaxis, NOT acute flares)', 'Hyperuricaemia (tumour lysis syndrome prevention)', 'Uric acid nephrolithiasis', 'Lesch-Nyhan syndrome'],
    sideEffects: ['Acute gout flare (in first 3-6 months of therapy — initiate with colchicine/NSAID cover)', 'Rash (common)', 'Stevens-Johnson Syndrome / DRESS (rare, serious — screen for HLA-B*5801 in Han Chinese, Korean, Thai)', 'GI upset', 'Renal impairment'],
    contraindications: ['Acute gout flare (start only after flare resolves)', 'HLA-B*5801 carriers (Asian populations) — high risk of severe hypersensitivity'],
    foodInteractions: ['Take after meals to reduce GI upset. Increase fluid intake (2-3L/day) to prevent kidney stones. Avoid purine-rich foods and alcohol.'],
    monitoring: ['Serum uric acid (target < 6 mg/dL)', 'Skin rash monitoring', 'Renal and hepatic function', 'CBC'],
    halfLife: '1–2h (allopurinol), 18–30h (oxypurinol active metabolite)', route: 'Oral', category: 'antigout',
    interactionIds: [],
  },
  {
    id: 26, name: 'Doxycycline', class: 'Antibiotic (Tetracycline)',
    min: 100, max: 200, maxDaily: 400,
    freq: ['OD', 'BD'], pregnancy: 'D',
    brands: ['Vibramycin', 'Doxy-1', 'Biodoxi', 'Doxt'],
    mechanism: 'Binds to 30S ribosomal subunit, inhibiting bacterial protein synthesis. Bacteriostatic. Broad-spectrum including atypicals, rickettsiae, spirochaetes, and protozoa.',
    indications: ['Atypical pneumonia (Mycoplasma, Legionella)', 'Malaria prophylaxis', 'Lyme disease', 'Acne vulgaris (long-term low-dose)', 'STIs (Chlamydia)', 'Rickettsia infections', 'Brucellosis'],
    sideEffects: ['Photosensitivity (avoid sun exposure)', 'Oesophageal irritation/ulceration (sit upright after taking)', 'Nausea', 'Permanent tooth discolouration (children)', 'Intracranial hypertension (pseudotumor cerebri)', 'Vaginal candidiasis'],
    contraindications: ['Pregnancy (bone/tooth damage)', 'Children < 8 years', 'Hypersensitivity to tetracyclines'],
    foodInteractions: ['Take with plenty of water. Stay upright 30 min after dose (avoid oesophageal ulcers). Avoid dairy, antacids, iron, calcium 2h before and after (chelation reduces absorption). Use sunscreen.'],
    monitoring: ['Photosensitivity', 'Hepatic function with prolonged use', 'Complete course'],
    halfLife: '16–22 hours', route: 'Oral/IV', category: 'antibiotic',
    interactionIds: [],
  },
  {
    id: 27, name: 'Pantoprazole', class: 'Proton Pump Inhibitor (PPI)',
    min: 20, max: 40, maxDaily: 80,
    freq: ['OD', 'BD'], pregnancy: 'B',
    brands: ['Pantocid', 'Protonix', 'Pan-D (with domperidone)', 'Pantop'],
    mechanism: 'Irreversible PPI — same mechanism as omeprazole. Less CYP2C19 interaction than omeprazole (preferred with clopidogrel).',
    indications: ['GERD', 'Peptic ulcer disease', 'H. pylori eradication', 'NSAID-induced ulcer prevention (gastric protection)', 'Preferred PPI with clopidogrel (less interaction)'],
    sideEffects: ['Headache', 'Nausea', 'Diarrhoea', 'Hypomagnesaemia', 'C. difficile risk', 'Bone fractures (prolonged use)'],
    contraindications: ['Concurrent rilpivirine', 'Hypersensitivity to PPIs'],
    foodInteractions: ['Take 30–60 min before meal. Do NOT crush or chew tablets.'],
    monitoring: ['Magnesium levels (long-term)', 'Vitamin B12 annually'],
    halfLife: '1–2 hours', route: 'Oral/IV', category: 'ppi',
    interactionIds: [],
  },
  {
    id: 28, name: 'Amiodarone', class: 'Antiarrhythmic (Class III)',
    min: 100, max: 200, maxDaily: 400,
    freq: ['OD', 'BD'], pregnancy: 'D',
    brands: ['Cordarone', 'Pacerone', 'Amiodar', 'Tachyra'],
    mechanism: 'Complex mechanism: primarily prolongs cardiac action potential (blocks K⁺ channels), also blocks Na⁺ and Ca²⁺ channels, and has α- and β-adrenergic blocking properties. Most effective antiarrhythmic.',
    indications: ['Ventricular fibrillation/tachycardia', 'Atrial fibrillation (rhythm control)', 'Life-threatening arrhythmias refractory to other agents', 'ACLS cardiac arrest protocol'],
    sideEffects: ['Pulmonary toxicity (interstitial pneumonitis — serious)', 'Thyroid dysfunction (hypo and hyperthyroidism)', 'Photosensitivity and slate-grey discolouration', 'Corneal microdeposits (almost universal)', 'Hepatotoxicity', 'Peripheral neuropathy', 'QT prolongation and TdP'],
    contraindications: ['Sinus bradycardia', 'High-degree AV block (without pacemaker)', 'Pre-existing thyroid disease (relative)', 'Concurrent QT-prolonging drugs', 'Iodine hypersensitivity'],
    foodInteractions: ['Avoid grapefruit. Avoid high-fat meals (increase absorption erratically). Consistent administration time.'],
    monitoring: ['TFTs (TSH) every 6 months', 'LFTs every 6 months', 'CXR + DLCO annually (pulmonary)', 'Slit-lamp eye examination', 'ECG (QT interval)', 'Electrolytes'],
    halfLife: '40–55 DAYS (extremely long)', route: 'Oral/IV', category: 'antiarrhythmic',
    interactionIds: [3],
    criticalNote: 'Most drug interactions of any common medicine. Check ALL concurrent medications. Tissue half-life means effects persist months after stopping.',
  },
  {
    id: 29, name: 'Atenolol', class: 'Beta-1 Selective Blocker (Cardioselective)',
    min: 25, max: 100, maxDaily: 200,
    freq: ['OD', 'BD'], pregnancy: 'D',
    brands: ['Tenormin', 'Aten', 'Betacard', 'Lonol'],
    mechanism: 'Cardioselective β1-adrenergic blocker. Unlike metoprolol, atenolol is hydrophilic — does not cross blood-brain barrier (fewer CNS side effects like nightmares).',
    indications: ['Hypertension', 'Stable angina', 'Post-MI (secondary prevention)', 'Atrial fibrillation rate control', 'Migraine prophylaxis'],
    sideEffects: ['Bradycardia', 'Fatigue', 'Cold extremities', 'Hypotension', 'Erectile dysfunction', 'Bronchoconstriction (less than propranolol)'],
    contraindications: ['Severe bradycardia', 'AV block (2nd or 3rd degree)', 'Cardiogenic shock', 'Severe asthma (relative)'],
    foodInteractions: ['Can be taken with or without food. Avoid calcium-rich foods or antacids 2h after dose (may reduce absorption).'],
    monitoring: ['Heart rate and BP', 'ECG', 'Blood glucose (masks hypoglycaemia symptoms)'],
    halfLife: '6–7 hours', route: 'Oral/IV', category: 'beta_blocker',
    interactionIds: [],
  },
  {
    id: 30, name: 'Cetirizine', class: 'Antihistamine (2nd Generation, H1 Blocker)',
    min: 5, max: 10, maxDaily: 10,
    freq: ['OD'], pregnancy: 'B',
    brands: ['Zyrtec', 'Alerid', 'Okacet', 'Cetzine'],
    mechanism: 'Selective peripheral H1-histamine receptor antagonist. Does not cross blood-brain barrier significantly (non-sedating). Antipruritic and anti-allergic.',
    indications: ['Allergic rhinitis (seasonal and perennial)', 'Urticaria (hives)', 'Allergic conjunctivitis', 'Atopic dermatitis (adjunctive)', 'Angioedema (adjunctive)'],
    sideEffects: ['Somnolence (mild, less than 1st gen)', 'Dry mouth', 'Headache', 'Fatigue', 'QT prolongation (high doses)'],
    contraindications: ['Severe renal impairment (reduce dose)', 'Hypersensitivity to cetirizine or hydroxyzine'],
    foodInteractions: ['Can be taken with or without food. Avoid alcohol (enhances sedation). Take at bedtime if somnolence is an issue.'],
    monitoring: ['Sedation level', 'Renal function in CKD'],
    halfLife: '8–9 hours', route: 'Oral', category: 'antihistamine',
    interactionIds: [],
  },
];

// ═══════════════════════════════════════════════════════════════════
//  DRUG-DRUG INTERACTIONS — Clinical Database
//  8 major interactions with full clinical management
// ═══════════════════════════════════════════════════════════════════
const INTERACTIONS = [
  {
    id: 1, drugA: 5, drugB: 6, severity: 'severe',
    mechanism: 'Aspirin inhibits platelet COX-1 (antiplatelet) while warfarin inhibits vitamin K-dependent coagulation factors. Aspirin also displaces warfarin from plasma protein binding (albumin), increasing free warfarin concentration. Together: dual attack on haemostasis.',
    effect: 'Dramatically increased bleeding risk at all sites: gastrointestinal (commonest), intracranial (most dangerous), surgical, genitourinary. Risk of fatal haemorrhage. Even low-dose aspirin (75mg) increases major bleeding by 50% with warfarin.',
    management: 'AVOID routine combination. Justified only in specific high-risk scenarios (e.g., mechanical heart valve + AF + ACS post-PCI) under specialist supervision. If unavoidable: use minimum aspirin dose (75mg OD), prescribe PPI gastroprotection, monitor INR weekly, educate patient on bleeding signs. Emergency: reverse warfarin with Vitamin K and/or FFP.',
    clinicalPearl: 'The CURE trial showed dual therapy doubles major bleeding vs antiplatelet alone. Triple therapy (warfarin + aspirin + clopidogrel) carries even higher risk.',
  },
  {
    id: 2, drugA: 4, drugB: 8, severity: 'moderate',
    mechanism: 'Azithromycin inhibits CYP3A4 (though weakly) and P-glycoprotein. Atorvastatin is a CYP3A4 substrate. Inhibition reduces atorvastatin metabolism, increasing its plasma concentration and muscle exposure.',
    effect: 'Elevated atorvastatin AUC by up to 60%. Increased risk of myopathy (muscle pain/weakness) and rhabdomyolysis (potentially fatal muscle breakdown leading to acute kidney injury and hyperkalaemia).',
    management: 'Combination generally acceptable for short courses (5-day azithromycin) with caution. Consider temporarily reducing atorvastatin dose or switching to azithromycin alternative (amoxicillin for typical pathogens). Monitor for muscle pain, weakness, dark urine (myoglobinuria). Check CK if symptomatic. Stop statin immediately if rhabdomyolysis suspected.',
    clinicalPearl: 'Rhabdomyolysis risk: Simvastatin > Atorvastatin > Rosuvastatin > Pravastatin. Rosuvastatin or pravastatin preferred if macrolide essential.',
  },
  {
    id: 3, drugA: 6, drugB: 10, severity: 'severe',
    mechanism: 'NSAIDs (ibuprofen) impair prostaglandin-mediated platelet aggregation and cause gastric mucosal damage (COX-1 inhibition removes gastroprotective prostaglandins). NSAIDs can also displace warfarin from albumin binding and inhibit CYP2C9 (warfarin metabolism), raising INR unpredictably.',
    effect: 'Severe GI bleeding risk (peptic ulceration + impaired coagulation). Unpredictable INR fluctuation. AKI risk (NSAID-induced renal prostaglandin inhibition combined with anticoagulation).',
    management: 'CONTRAINDICATED as regular combination. Use paracetamol (1g up to QDS) as analgesic alternative — safe with warfarin at normal doses. If NSAID absolutely necessary: shortest course possible, gastroprotection with PPI (pantoprazole preferred), daily INR monitoring, reduce warfarin dose preemptively by 10-20%, monitor renal function.',
    clinicalPearl: '"Triple whammy" (ACE inhibitor + diuretic + NSAID) causes AKI in up to 1 in 1000 patients exposed. Adding warfarin makes it even more dangerous.',
  },
  {
    id: 4, drugA: 7, drugB: 10, severity: 'moderate',
    mechanism: 'NSAIDs blunt the antihypertensive effect of ACE inhibitors (prostaglandins mediate the vasodilatory response). NSAIDs also cause renal afferent arteriolar vasoconstriction, opposing the ACE inhibitor\'s renoprotective afferent dilation. Together: "Triple whammy" with diuretics.',
    effect: 'Loss of BP control (systolic BP may rise 3-5 mmHg even with occasional NSAID use). Acute kidney injury — especially in patients who are elderly, dehydrated, have CKD, or are on diuretics concurrently.',
    management: 'Prefer paracetamol for analgesia in ACE-inhibitor patients. If NSAID required: shortest duration, lowest dose, topical NSAID first (less systemic effect), monitor BP and U&E within 1 week. Hold diuretic if dehydration risk (sick-day rules). Avoid in CKD (eGFR < 60).',
    clinicalPearl: 'The combination of ACEI + diuretic + NSAID is known as the "triple whammy" and is responsible for a significant proportion of hospital admissions for AKI.',
  },
  {
    id: 5, drugA: 5, drugB: 17, severity: 'moderate',
    mechanism: 'Aspirin and clopidogrel both inhibit platelet aggregation via different mechanisms (COX-1 and P2Y12 respectively). Combined, they provide dual antiplatelet therapy (DAPT) with additive antiplatelet effect.',
    effect: 'Significantly increased risk of bleeding from all sites — particularly GI (most common) and intracranial. Annual major bleeding rate on DAPT: ~2-3% vs ~1% on single antiplatelet.',
    management: 'DAPT is appropriate and necessary in specific clinical contexts (ACS, post-PCI, post-stent). Duration: 12 months post-ACS, 1-3 months post-elective PCI. MANDATORY PPI gastroprotection (pantoprazole 40mg OD — avoid omeprazole with clopidogrel). Educate on bleeding signs. Peri-procedural management requires specialist input.',
    clinicalPearl: 'Use pantoprazole, NOT omeprazole, with clopidogrel. Omeprazole inhibits CYP2C19, reducing clopidogrel activation by 40%.',
  },
  {
    id: 6, drugA: 3, drugB: 28, severity: 'moderate',
    mechanism: 'Amiodarone inhibits renal tubular secretion of metformin via OCT2 and MATE1/2 transporters. Also inhibits CYP3A4 and P-gp. Net result: higher metformin plasma concentration and reduced elimination.',
    effect: 'Elevated metformin levels increase the risk of metformin-associated lactic acidosis (MALA) — rare but potentially fatal. Amiodarone-induced hypothyroidism can also worsen hyperglycaemia, requiring metformin dose increases paradoxically.',
    management: 'Reduce metformin dose by 25-50% when starting amiodarone. Monitor renal function closely (metformin renally cleared). Check lactate levels if GI symptoms or clinical deterioration. Maintain good hydration. Consider alternative antidiabetic if combination required long-term. Monitor TFTs (thyroid affects glucose metabolism).',
    clinicalPearl: 'MALA is very rare (< 10 cases/100,000 patient-years) but carries 30-50% mortality. Risk increases with renal impairment, dehydration, and iodinated contrast.',
  },
  {
    id: 7, drugA: 7, drugB: 13, severity: 'contraindicated',
    mechanism: 'ACE inhibitors (lisinopril) and ARBs (losartan) both block the renin-angiotensin-aldosterone system (RAAS), but at different points. Combining them does NOT provide additive BP reduction but DOES cause additive adverse effects.',
    effect: 'Dual RAAS blockade causes: hypotension (often profound), hyperkalaemia (serious arrhythmia risk), and acute kidney injury. The ONTARGET trial showed increased renal failure, dialysis, and cardiovascular events with combination vs. monotherapy.',
    management: 'CONTRAINDICATED in most patients. The ONTARGET trial definitively showed no additional CV benefit but significantly more harm. Exception: specialist-supervised heart failure management in selected cases. If patient is on both: STOP one agent, monitor BP, K⁺, and renal function closely.',
    clinicalPearl: 'The VA NEPHRON-D trial confirmed harm even in diabetic nephropathy, ending the concept of "renoprotective" dual RAAS blockade.',
  },
  {
    id: 8, drugA: 1, drugB: 4, severity: 'minor',
    mechanism: 'Some penicillins can inhibit CYP3A4 marginally, potentially slightly increasing atorvastatin exposure. The interaction is generally not clinically significant at standard doses.',
    effect: 'Minimal elevation in atorvastatin levels. Theoretical increased myopathy risk, but clinical reports are rare. Interaction is clinically insignificant in most patients.',
    management: 'No dose adjustment typically required. Continue both medications as prescribed. Monitor for unusual muscle pain during concurrent use (routine precaution). No need to change either drug for this interaction alone.',
    clinicalPearl: 'This interaction is listed as minor and rarely causes clinical problems. The benefit of treating the infection with amoxicillin outweighs minimal theoretical risk.',
  },
];

module.exports = { DRUGS, INTERACTIONS };
